# Generated by Django 3.2.9 on 2021-12-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message_list',
        ),
        migrations.AddField(
            model_name='message',
            name='message_list',
            field=models.ManyToManyField(blank=True, to='chats.MessageList'),
        ),
    ]
