# Generated by Django 3.2.9 on 2021-12-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_auto_20211213_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='owner_str',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
